package com.b4rrhh.employee.working_time.infrastructure.persistence;

import com.b4rrhh.rulesystem.agreementprofile.infrastructure.persistence.AgreementCatalogLookupAdapter;
import com.b4rrhh.rulesystem.agreementprofile.infrastructure.persistence.AgreementProfileEntity;
import com.b4rrhh.rulesystem.infrastructure.persistence.RuleEntityEntity;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;
import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

@DataJpaTest(properties = {
    "spring.jpa.hibernate.ddl-auto=none",
    "spring.flyway.enabled=false",
    "spring.datasource.url=jdbc:h2:mem:agreement-annual-hours-lookup;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE",
    "spring.datasource.driver-class-name=org.h2.Driver",
    "spring.datasource.username=sa",
    "spring.datasource.password="
})
@Import({AgreementAnnualHoursLookupAdapter.class, AgreementCatalogLookupAdapter.class})
class AgreementAnnualHoursLookupAdapterTest {

    private static final String RULE_SYSTEM_CODE = "ESP";
    private static final String REAL_AGREEMENT_CODE = "99002405011982";
    private static final String AGREEMENT_WITHOUT_PROFILE_CODE = "99002405011983";

    @Autowired
    private TestEntityManager entityManager;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private AgreementAnnualHoursLookupAdapter adapter;

    @BeforeEach
    void setUpSchema() {
    jdbcTemplate.execute("create schema if not exists rulesystem");
    jdbcTemplate.execute("drop table if exists rulesystem.agreement_profile");
    jdbcTemplate.execute("drop table if exists rulesystem.rule_entity");
    jdbcTemplate.execute("drop table if exists rulesystem.rule_entity_type");
    jdbcTemplate.execute("drop table if exists rulesystem.rule_system");

    jdbcTemplate.execute("""
        create table rulesystem.rule_system (
            code varchar(5) primary key,
            name varchar(100) not null,
            country_code char(3) not null,
            active boolean not null,
            created_at timestamp not null default current_timestamp,
            updated_at timestamp not null default current_timestamp
        )
        """);
    jdbcTemplate.execute("""
        create table rulesystem.rule_entity_type (
            code varchar(30) primary key,
            name varchar(100) not null,
            active boolean not null,
            created_at timestamp not null default current_timestamp,
            updated_at timestamp not null default current_timestamp
        )
        """);
    jdbcTemplate.execute("""
        create table rulesystem.rule_entity (
            id bigint generated by default as identity primary key,
            rule_system_code varchar(5) not null,
            rule_entity_type_code varchar(30) not null,
            code varchar(30) not null,
            name varchar(100) not null,
            description varchar(500),
            active boolean not null,
            start_date date not null,
            end_date date,
            created_at timestamp not null default current_timestamp,
            updated_at timestamp not null default current_timestamp,
            constraint uk_rule_entity_business unique (rule_system_code, rule_entity_type_code, code),
            constraint fk_rule_entity_rule_system foreign key (rule_system_code) references rulesystem.rule_system(code),
            constraint fk_rule_entity_type foreign key (rule_entity_type_code) references rulesystem.rule_entity_type(code)
        )
        """);
    jdbcTemplate.execute("""
        create table rulesystem.agreement_profile (
            id bigint generated by default as identity primary key,
            agreement_rule_entity_id bigint not null,
            official_agreement_number varchar(50) not null,
            display_name varchar(200) not null,
            short_name varchar(50),
            annual_hours numeric(7, 2) not null,
            is_active boolean not null,
            created_at timestamp not null default current_timestamp,
            updated_at timestamp not null default current_timestamp,
            constraint uk_agreement_profile_rule_entity unique (agreement_rule_entity_id),
            constraint fk_agreement_profile_rule_entity foreign key (agreement_rule_entity_id) references rulesystem.rule_entity(id)
        )
        """);

    jdbcTemplate.update(
        "insert into rulesystem.rule_system (code, name, country_code, active) values (?, ?, ?, ?)",
        RULE_SYSTEM_CODE,
        "Spain Personnel Administration",
        "ESP",
        true
    );
    jdbcTemplate.update(
        "insert into rulesystem.rule_entity_type (code, name, active) values (?, ?, ?)",
        "AGREEMENT",
        "Agreement",
        true
    );
    }

    @Test
    void resolveAnnualHoursReturnsConfiguredHoursForPersistedRealisticAgreementCode() {
    RuleEntityEntity agreement = agreementEntity(
        REAL_AGREEMENT_CODE,
        "Convenio colectivo general de centros y servicios de atencion a personas con discapacidad"
    );
        entityManager.persist(agreement);
        entityManager.flush();

    AgreementProfileEntity profile = profileEntity(agreement.getId(), REAL_AGREEMENT_CODE,
                "Convenio colectivo general centros atencion personas con discapacidad",
                new BigDecimal("1736.00"));
        entityManager.persist(profile);
        entityManager.flush();

    BigDecimal result = adapter.resolveAnnualHours(RULE_SYSTEM_CODE, REAL_AGREEMENT_CODE);

        assertEquals(0, new BigDecimal("1736.00").compareTo(result));
    }

    @Test
    void resolveAnnualHoursThrowsWhenAgreementNotFound() {
        assertThrows(IllegalStateException.class,
            () -> adapter.resolveAnnualHours(RULE_SYSTEM_CODE, "UNKNOWN_CODE"),
                "Should throw when agreement is not in catalog");
    }

    @Test
    void resolveAnnualHoursThrowsWhenProfileMissingForKnownAgreement() {
        RuleEntityEntity agreement = agreementEntity(
            AGREEMENT_WITHOUT_PROFILE_CODE,
            "Convenio sin agreement_profile"
        );
        entityManager.persist(agreement);
        entityManager.flush();

        assertThrows(IllegalStateException.class,
            () -> adapter.resolveAnnualHours(RULE_SYSTEM_CODE, AGREEMENT_WITHOUT_PROFILE_CODE),
                "Should throw when agreement exists but has no profile configured");
    }

    private RuleEntityEntity agreementEntity(String code, String name) {
        RuleEntityEntity entity = new RuleEntityEntity();
        entity.setRuleSystemCode(RULE_SYSTEM_CODE);
        entity.setRuleEntityTypeCode("AGREEMENT");
        entity.setCode(code);
        entity.setName(name);
        entity.setActive(true);
        entity.setStartDate(LocalDate.of(2023, 1, 1));
        return entity;
    }

    private AgreementProfileEntity profileEntity(Long ruleEntityId, String officialNumber,
                                                  String displayName, BigDecimal annualHours) {
        AgreementProfileEntity entity = new AgreementProfileEntity();
        entity.setAgreementRuleEntityId(ruleEntityId);
        entity.setOfficialAgreementNumber(officialNumber);
        entity.setDisplayName(displayName);
        entity.setAnnualHours(annualHours);
        entity.setIsActive(true);
        return entity;
    }
}

