package com.b4rrhh.employee.working_time.infrastructure.persistence;

import com.b4rrhh.employee.employee.infrastructure.persistence.EmployeeEntity;
import com.b4rrhh.employee.labor_classification.infrastructure.persistence.LaborClassificationEntity;
import com.b4rrhh.employee.working_time.application.port.EmployeeAgreementContext;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false",
        "spring.datasource.url=jdbc:h2:mem:employee-agreement-context;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password="
})
@Import(EmployeeAgreementContextLookupAdapter.class)
class EmployeeAgreementContextLookupAdapterTest {

    private static final String RULE_SYSTEM_CODE = "ESP";

    @Autowired
    private TestEntityManager entityManager;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private EmployeeAgreementContextLookupAdapter adapter;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists employee");
        jdbcTemplate.execute("drop table if exists employee.labor_classification");
        jdbcTemplate.execute("drop table if exists employee.employee");

        jdbcTemplate.execute("""
                create table employee.employee (
                    id bigint generated by default as identity primary key,
                    rule_system_code varchar(5) not null,
                    employee_type_code varchar(30) not null,
                    employee_number varchar(15) not null,
                    first_name varchar(100) not null,
                    last_name_1 varchar(100) not null,
                    last_name_2 varchar(100),
                    preferred_name varchar(300),
                    status varchar(30) not null,
                    created_at timestamp not null default current_timestamp,
                    updated_at timestamp not null default current_timestamp,
                    constraint uk_employee_business unique (rule_system_code, employee_type_code, employee_number)
                )
                """);
        jdbcTemplate.execute("""
                create table employee.labor_classification (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    agreement_code varchar(30) not null,
                    agreement_category_code varchar(30) not null,
                    start_date date not null,
                    end_date date,
                    created_at timestamp not null default current_timestamp,
                    updated_at timestamp not null default current_timestamp,
                    constraint uk_labor_classification_business unique (employee_id, start_date),
                    constraint fk_labor_classification_employee foreign key (employee_id) references employee.employee(id)
                )
                """);
    }

    @Test
    void resolveContextReturnsCorrectAgreementContextAtEffectiveDate() {
        EmployeeEntity employee = employeeEntity(RULE_SYSTEM_CODE, "INTERNAL", "EMP001");
        entityManager.persist(employee);
        entityManager.flush();

        LaborClassificationEntity classification = laborClassification(
                employee.getId(), "99002405011982", "99002405-G2",
                LocalDate.of(2024, 1, 1), null);
        entityManager.persist(classification);
        entityManager.flush();

        EmployeeAgreementContext result = adapter.resolveContext(employee.getId(), LocalDate.of(2026, 1, 10));

        assertEquals(RULE_SYSTEM_CODE, result.ruleSystemCode());
        assertEquals("99002405011982", result.agreementCode());
    }

    @Test
        void resolveContextPicksLatestValidClassificationWhenMoreThanOneRecordMatchesDate() {
        EmployeeEntity employee = employeeEntity(RULE_SYSTEM_CODE, "INTERNAL", "EMP002");
        entityManager.persist(employee);
        entityManager.flush();

        LaborClassificationEntity initial = laborClassification(
            employee.getId(), "99002405011981", "99002405-G1",
            LocalDate.of(2024, 1, 1), null);
        LaborClassificationEntity replacement = laborClassification(
                employee.getId(), "99002405011982", "99002405-G1",
            LocalDate.of(2024, 6, 1), null);
        entityManager.persist(initial);
        entityManager.persist(replacement);
        entityManager.flush();

        EmployeeAgreementContext result = adapter.resolveContext(employee.getId(), LocalDate.of(2024, 7, 1));

        assertEquals("99002405011982", result.agreementCode());
    }

    @Test
    void resolveContextThrowsWhenNoClassificationExistsAtDate() {
        EmployeeEntity employee = employeeEntity(RULE_SYSTEM_CODE, "INTERNAL", "EMP003");
        entityManager.persist(employee);
        entityManager.flush();

        LaborClassificationEntity classification = laborClassification(
                employee.getId(), "99002405011982", "99002405-G2",
                LocalDate.of(2024, 1, 1), LocalDate.of(2024, 12, 31));
        entityManager.persist(classification);
        entityManager.flush();

        // Effective date is after the classification end_date
        assertThrows(IllegalStateException.class,
                () -> adapter.resolveContext(employee.getId(), LocalDate.of(2026, 1, 10)),
                "Should throw when no valid labor classification found at effective date");
    }

    @Test
    void resolveContextThrowsWhenEmployeeHasNoClassificationsAtAll() {
        EmployeeEntity employee = employeeEntity(RULE_SYSTEM_CODE, "INTERNAL", "EMP004");
        entityManager.persist(employee);
        entityManager.flush();

        assertThrows(IllegalStateException.class,
                () -> adapter.resolveContext(employee.getId(), LocalDate.of(2026, 1, 10)),
                "Should throw when employee has no labor classifications");
    }

    private EmployeeEntity employeeEntity(String ruleSystemCode, String employeeTypeCode, String employeeNumber) {
        EmployeeEntity entity = new EmployeeEntity();
        entity.setRuleSystemCode(ruleSystemCode);
        entity.setEmployeeTypeCode(employeeTypeCode);
        entity.setEmployeeNumber(employeeNumber);
        entity.setFirstName("Test");
        entity.setLastName1("Employee");
        entity.setStatus("ACTIVE");
        return entity;
    }

    private LaborClassificationEntity laborClassification(Long employeeId, String agreementCode,
                                                           String agreementCategoryCode,
                                                           LocalDate startDate, LocalDate endDate) {
        LaborClassificationEntity entity = new LaborClassificationEntity();
        entity.setEmployeeId(employeeId);
        entity.setAgreementCode(agreementCode);
        entity.setAgreementCategoryCode(agreementCategoryCode);
        entity.setStartDate(startDate);
        entity.setEndDate(endDate);
        return entity;
    }
}
