spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/b4rrhh
    username: b4rrhh
    password: b4rrhh
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.flywaydb: info