package com.b4rrhh.employee.lifecycle.application.usecase;

import com.b4rrhh.employee.contract.application.usecase.CreateContractUseCase;
import com.b4rrhh.employee.cost_center.application.usecase.CreateCostCenterDistributionUseCase;
import com.b4rrhh.employee.employee.application.usecase.CreateEmployeeService;
import com.b4rrhh.employee.employee.application.usecase.CreateEmployeeUseCase;
import com.b4rrhh.employee.employee.domain.port.EmployeeRepository;
import com.b4rrhh.employee.employee.infrastructure.persistence.EmployeePersistenceAdapter;
import com.b4rrhh.employee.lifecycle.application.command.HireEmployeeCommand;
import com.b4rrhh.employee.lifecycle.domain.exception.HireEmployeeCatalogValueInvalidException;
import com.b4rrhh.employee.presence.application.usecase.CreatePresenceCommand;
import com.b4rrhh.employee.presence.application.usecase.CreatePresenceUseCase;
import com.b4rrhh.employee.presence.domain.model.Presence;
import com.b4rrhh.employee.workcenter.application.usecase.CreateWorkCenterUseCase;
import com.b4rrhh.employee.workcenter.domain.exception.WorkCenterCatalogValueInvalidException;
import com.b4rrhh.employee.labor_classification.application.usecase.CreateLaborClassificationUseCase;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
@Transactional(propagation = Propagation.NOT_SUPPORTED)
@Import({
        EmployeePersistenceAdapter.class,
        HireEmployeeService.class,
        HireEmployeeServiceRollbackIntegrationTest.HireEmployeeRollbackTestConfig.class
})
class HireEmployeeServiceRollbackIntegrationTest {

    @Autowired
    private HireEmployeeService service;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists employee");
        jdbcTemplate.execute("drop table if exists employee.employee");

        jdbcTemplate.execute("""
                create table employee.employee (
                    id bigint generated by default as identity primary key,
                    rule_system_code varchar(5) not null,
                    employee_type_code varchar(30) not null,
                    employee_number varchar(15) not null,
                    first_name varchar(100) not null,
                    last_name_1 varchar(100) not null,
                    last_name_2 varchar(100),
                    preferred_name varchar(300),
                    status varchar(30) not null,
                    created_at timestamp not null,
                    updated_at timestamp not null,
                    constraint uk_employee_business_key unique (rule_system_code, employee_type_code, employee_number)
                )
                """);
    }

    @Test
    void rollsBackCreatedEmployeeWhenAnySubOperationFails() {
        HireEmployeeCommand command = new HireEmployeeCommand(
                "ESP",
                "INTERNAL",
                "EMP001",
                "Ana",
                "Lopez",
                null,
                "Ani",
                LocalDate.of(2026, 3, 23),
                "HIRE",
                "COMP",
                "BAD_WC",
                new HireEmployeeCommand.HireEmployeeContractCommand("CON", "SUB"),
                new HireEmployeeCommand.HireEmployeeLaborClassificationCommand("AGR", "CAT"),
                null
        );

        assertThrows(HireEmployeeCatalogValueInvalidException.class, () -> service.hire(command));

        Long employeeCount = jdbcTemplate.queryForObject(
                "select count(*) from employee.employee where rule_system_code = ? and employee_type_code = ? and employee_number = ?",
                Long.class,
                "ESP",
                "INTERNAL",
                "EMP001"
        );

        assertEquals(0L, employeeCount);
    }

    @TestConfiguration
    static class HireEmployeeRollbackTestConfig {

        @Bean
        CreateEmployeeUseCase createEmployeeUseCase(EmployeeRepository employeeRepository) {
            return new CreateEmployeeService(employeeRepository);
        }

        @Bean
        CreatePresenceUseCase createPresenceUseCase() {
            return new CreatePresenceUseCase() {
                @Override
                public Presence create(CreatePresenceCommand command) {
                    return new Presence(
                            10L,
                            1L,
                            1,
                            command.companyCode(),
                            command.entryReasonCode(),
                            command.exitReasonCode(),
                            command.startDate(),
                            command.endDate(),
                            java.time.LocalDateTime.now(),
                            java.time.LocalDateTime.now()
                    );
                }
            };
        }

        @Bean
        CreateLaborClassificationUseCase createLaborClassificationUseCase() {
            return command -> null;
        }

        @Bean
        CreateContractUseCase createContractUseCase() {
            return command -> null;
        }

        @Bean
        CreateWorkCenterUseCase createWorkCenterUseCase() {
            return command -> {
                if ("BAD_WC".equals(command.workCenterCode())) {
                    throw new WorkCenterCatalogValueInvalidException("workCenterCode", command.workCenterCode());
                }
                return null;
            };
        }

        @Bean
        CreateCostCenterDistributionUseCase createCostCenterDistributionUseCase() {
            return command -> null;
        }
    }
}
