package com.b4rrhh.employee.lifecycle.application.usecase;

import com.b4rrhh.employee.contract.application.command.CloseContractCommand;
import com.b4rrhh.employee.contract.application.command.ListEmployeeContractsCommand;
import com.b4rrhh.employee.contract.application.usecase.CloseContractUseCase;
import com.b4rrhh.employee.contract.application.usecase.ListEmployeeContractsUseCase;
import com.b4rrhh.employee.contract.domain.model.Contract;
import com.b4rrhh.employee.employee.application.usecase.GetEmployeeByBusinessKeyUseCase;
import com.b4rrhh.employee.employee.domain.port.EmployeeRepository;
import com.b4rrhh.employee.employee.infrastructure.persistence.EmployeePersistenceAdapter;
import com.b4rrhh.employee.labor_classification.application.command.CloseLaborClassificationCommand;
import com.b4rrhh.employee.labor_classification.application.command.ListEmployeeLaborClassificationsCommand;
import com.b4rrhh.employee.labor_classification.application.usecase.CloseLaborClassificationUseCase;
import com.b4rrhh.employee.labor_classification.application.usecase.ListEmployeeLaborClassificationsUseCase;
import com.b4rrhh.employee.labor_classification.domain.model.LaborClassification;
import com.b4rrhh.employee.lifecycle.application.command.TerminateEmployeeCommand;
import com.b4rrhh.employee.lifecycle.domain.exception.TerminateEmployeeConflictException;
import com.b4rrhh.employee.presence.application.usecase.ClosePresenceCommand;
import com.b4rrhh.employee.presence.application.usecase.ClosePresenceUseCase;
import com.b4rrhh.employee.presence.application.usecase.ListEmployeePresencesUseCase;
import com.b4rrhh.employee.presence.domain.model.Presence;
import com.b4rrhh.employee.workcenter.application.usecase.CloseWorkCenterCommand;
import com.b4rrhh.employee.workcenter.application.usecase.CloseWorkCenterUseCase;
import com.b4rrhh.employee.workcenter.application.usecase.ListEmployeeWorkCentersUseCase;
import com.b4rrhh.employee.workcenter.domain.model.WorkCenter;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
@Transactional(propagation = Propagation.NOT_SUPPORTED)
@Import({
        EmployeePersistenceAdapter.class,
        TerminateEmployeeService.class,
        TerminateEmployeeServiceRollbackIntegrationTest.TerminateEmployeeRollbackTestConfig.class
})
class TerminateEmployeeServiceRollbackIntegrationTest {

    @Autowired
    private TerminateEmployeeService service;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists employee");
        jdbcTemplate.execute("drop table if exists employee.employee");

        jdbcTemplate.execute("""
                create table employee.employee (
                    id bigint generated by default as identity primary key,
                    rule_system_code varchar(5) not null,
                    employee_type_code varchar(30) not null,
                    employee_number varchar(15) not null,
                    first_name varchar(100) not null,
                    last_name_1 varchar(100) not null,
                    last_name_2 varchar(100),
                    preferred_name varchar(300),
                    status varchar(30) not null,
                    created_at timestamp not null,
                    updated_at timestamp not null,
                    constraint uk_employee_business_key unique (rule_system_code, employee_type_code, employee_number)
                )
                """);

        jdbcTemplate.update(
                "insert into employee.employee (rule_system_code, employee_type_code, employee_number, first_name, last_name_1, status, created_at, updated_at) values (?, ?, ?, ?, ?, ?, current_timestamp, current_timestamp)",
                "ESP",
                "INTERNAL",
                "EMP001",
                "Ana",
                "Lopez",
                "ACTIVE"
        );
    }

    @Test
    void rollsBackEmployeeStatusWhenPostConditionFailsAfterTermination() {
        TerminateEmployeeCommand command = new TerminateEmployeeCommand(
                "ESP",
                "INTERNAL",
                "EMP001",
                LocalDate.of(2026, 3, 31),
                "VOL"
        );

        assertThrows(TerminateEmployeeConflictException.class, () -> service.terminate(command));

        String persistedStatus = jdbcTemplate.queryForObject(
                "select status from employee.employee where rule_system_code = ? and employee_type_code = ? and employee_number = ?",
                String.class,
                "ESP",
                "INTERNAL",
                "EMP001"
        );

        assertEquals("ACTIVE", persistedStatus);
    }

    @TestConfiguration
    static class TerminateEmployeeRollbackTestConfig {

        @Bean
        GetEmployeeByBusinessKeyUseCase getEmployeeByBusinessKeyUseCase(EmployeeRepository employeeRepository) {
            return (ruleSystemCode, employeeTypeCode, employeeNumber) -> employeeRepository
                    .findByRuleSystemCodeAndEmployeeTypeCodeAndEmployeeNumber(
                            ruleSystemCode,
                            employeeTypeCode,
                            employeeNumber
                    );
        }

        @Bean
        ListEmployeePresencesUseCase listEmployeePresencesUseCase() {
            return new ListEmployeePresencesUseCase() {
                private final AtomicInteger calls = new AtomicInteger(0);

                @Override
                public List<Presence> listByEmployeeBusinessKey(
                        String ruleSystemCode,
                        String employeeTypeCode,
                        String employeeNumber
                ) {
                    if (calls.incrementAndGet() == 1) {
                        return List.of(activePresence());
                    }

                    // Simulates pre-existing inconsistency that remains after attempted close.
                    return List.of(activePresence());
                }

                private Presence activePresence() {
                    return new Presence(
                            10L,
                            100L,
                            1,
                            "COMP",
                            "HIRE",
                            null,
                            LocalDate.of(2026, 1, 1),
                            null,
                            LocalDateTime.now(),
                            LocalDateTime.now()
                    );
                }
            };
        }

        @Bean
        ListEmployeeContractsUseCase listEmployeeContractsUseCase() {
            return command -> List.of(new Contract(
                    100L,
                    "IND",
                    "FT1",
                    LocalDate.of(2026, 1, 1),
                    null
            ));
        }

        @Bean
        ListEmployeeLaborClassificationsUseCase listEmployeeLaborClassificationsUseCase() {
            return command -> List.of(new LaborClassification(
                    100L,
                    "AGR",
                    "CAT",
                    LocalDate.of(2026, 1, 1),
                    null
            ));
        }

        @Bean
        ListEmployeeWorkCentersUseCase listEmployeeWorkCentersUseCase() {
            return (ruleSystemCode, employeeTypeCode, employeeNumber) -> List.of(new WorkCenter(
                    20L,
                    100L,
                    1,
                    "WC1",
                    LocalDate.of(2026, 1, 1),
                    null,
                    LocalDateTime.now(),
                    LocalDateTime.now()
            ));
        }

        @Bean
        CloseWorkCenterUseCase closeWorkCenterUseCase() {
            return command -> new WorkCenter(
                    20L,
                    100L,
                    command.workCenterAssignmentNumber(),
                    "WC1",
                    LocalDate.of(2026, 1, 1),
                    command.endDate(),
                    LocalDateTime.now(),
                    LocalDateTime.now()
            );
        }

        @Bean
        CloseLaborClassificationUseCase closeLaborClassificationUseCase() {
            return command -> new LaborClassification(
                    100L,
                    "AGR",
                    "CAT",
                    command.startDate(),
                    command.endDate()
            );
        }

        @Bean
        CloseContractUseCase closeContractUseCase() {
            return command -> new Contract(
                    100L,
                    "IND",
                    "FT1",
                    command.startDate(),
                    command.endDate()
            );
        }

        @Bean
        ClosePresenceUseCase closePresenceUseCase() {
            return command -> new Presence(
                    10L,
                    100L,
                    command.presenceNumber(),
                    "COMP",
                    "HIRE",
                    command.exitReasonCode(),
                    LocalDate.of(2026, 1, 1),
                    command.endDate(),
                    LocalDateTime.now(),
                    LocalDateTime.now()
            );
        }
    }
}
