package com.b4rrhh.employee.workcenter.infrastructure.persistence;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
class SpringDataWorkCenterRepositoryIntegrationTest {

    @Autowired
    private SpringDataWorkCenterRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("create schema if not exists employee");
        jdbcTemplate.execute("drop table if exists employee.work_center");
        jdbcTemplate.execute("""
                create table employee.work_center (
                    id bigint generated by default as identity primary key,
                    employee_id bigint not null,
                    work_center_assignment_number integer not null,
                    work_center_code varchar(30) not null,
                    start_date date not null,
                    end_date date,
                    created_at timestamp not null,
                    updated_at timestamp not null,
                    constraint uk_work_center_assignment_number unique (employee_id, work_center_assignment_number),
                    constraint chk_work_center_dates check (end_date is null or start_date <= end_date)
                )
                """);
    }

    @Test
    void enforcesUniqueConstraintPerEmployeeAndAssignmentNumber() {
        repository.saveAndFlush(workCenterEntity(10L, 1, LocalDate.of(2026, 1, 1), null));

        assertThrows(
                DataIntegrityViolationException.class,
                () -> repository.saveAndFlush(workCenterEntity(10L, 1, LocalDate.of(2026, 2, 1), null))
        );
    }

    @Test
    void detectsOverlappingPeriodsUsingRepositoryQuery() {
        repository.saveAndFlush(workCenterEntity(10L, 1, LocalDate.of(2026, 1, 1), LocalDate.of(2026, 1, 31)));

        boolean overlap = repository.existsOverlappingPeriod(
                10L,
                LocalDate.of(2026, 1, 15),
                LocalDate.of(2026, 2, 15),
                LocalDate.of(9999, 12, 31)
        );

        assertTrue(overlap);
    }

    private WorkCenterEntity workCenterEntity(Long employeeId, Integer assignmentNumber, LocalDate startDate, LocalDate endDate) {
        WorkCenterEntity entity = new WorkCenterEntity();
        entity.setEmployeeId(employeeId);
        entity.setWorkCenterAssignmentNumber(assignmentNumber);
        entity.setWorkCenterCode("MADRID_HQ");
        entity.setStartDate(startDate);
        entity.setEndDate(endDate);
        return entity;
    }
}